# Workflow to build and push Docker image to AWS ECR

name: Build and Push Docker Image to AWS ECR

on:
    push:
        branches:
            - main

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set VITE_API_URL from secret
          run: echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> $GITHUB_ENV  

        - run: npm ci && npm run build

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Login to Amazon ECR Public
          run: |
            aws ecr-public get-login-password --region us-east-1 \
              | docker login --username AWS --password-stdin public.ecr.aws
        
        - run: aws s3 sync dist/ s3://${{ vars.S3_BUCKET }}/ --delete

        - run: aws cloudfront create-invalidation --distribution-id ${{ vars.CF_DIST_ID }} --paths "/*"
